<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Module;
use App\Models\Component;
use App\Models\ComponentOption;

class ModuleSeeder extends Seeder
{
    public function run(): void
    {
        // ============================================
        // MÓDULO HEADER PROFESIONAL
        // ============================================
        $header = Module::create([
            'name' => 'Header',
            'description' => 'Encabezado del sitio con soporte para modo claro/oscuro',
            'slug' => 'header',
        ]);

        // Header components
        $headerComponents = [
            // Logos por modo
            [
                'module_id' => $header->id,
                'label' => 'Logo (modo claro)',
                'name' => 'logo_light',
                'type' => 'image',
                'color_mode' => 'light',
                'placeholder' => 'URL del logo versión clara',
                'is_required' => true,
                'order' => 1,
                'validation_rules' => json_encode(['required', 'image', 'max:2048']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Logo (modo oscuro)',
                'name' => 'logo_dark',
                'type' => 'image',
                'color_mode' => 'dark',
                'placeholder' => 'URL del logo versión oscura',
                'is_required' => false,
                'order' => 2,
                'validation_rules' => json_encode(['nullable', 'image', 'max:2048']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Colores de fondo por modo
            [
                'module_id' => $header->id,
                'label' => 'Color de fondo (modo claro)',
                'name' => 'bg_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#ffffff',
                'is_required' => true,
                'order' => 3,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Color de fondo (modo oscuro)',
                'name' => 'bg_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#1a1a1a',
                'is_required' => true,
                'order' => 4,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Colores de texto por modo
            [
                'module_id' => $header->id,
                'label' => 'Color del texto (modo claro)',
                'name' => 'text_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#000000',
                'is_required' => true,
                'order' => 5,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Color del texto (modo oscuro)',
                'name' => 'text_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#ffffff',
                'is_required' => true,
                'order' => 6,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Menú y configuración
            [
                'module_id' => $header->id,
                'label' => 'Elementos del menú',
                'name' => 'menu_items',
                'type' => 'external',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 7,
                'validation_rules' => json_encode(['nullable', 'array']),
                'data_source' => env('ERP_API_URL') . '/menu-items',
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Altura del header',
                'name' => 'header_height',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '80',
                'is_required' => false,
                'order' => 8,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'options' => json_encode(['min' => 40, 'max' => 200, 'step' => 1, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Posición del logo',
                'name' => 'logo_position',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'left',
                'is_required' => false,
                'order' => 9,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Component::insert($headerComponents);

        // Opciones para posición del logo
        $logoPositionComp = Component::where('module_id', $header->id)
            ->where('name', 'logo_position')
            ->first();
        if ($logoPositionComp) {
            ComponentOption::insert([
                [
                    'component_id' => $logoPositionComp->id,
                    'label' => 'Izquierda',
                    'value' => 'left',
                    'order' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'component_id' => $logoPositionComp->id,
                    'label' => 'Centro',
                    'value' => 'center',
                    'order' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'component_id' => $logoPositionComp->id,
                    'label' => 'Derecha',
                    'value' => 'right',
                    'order' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        // ============================================
        // MÓDULO HERO PROFESIONAL
        // ============================================
        $hero = Module::create([
            'name' => 'Hero',
            'description' => 'Sección principal con control total de imagen, colores y efectos',
            'slug' => 'hero',
        ]);

        $heroComponents = [
            // Contenido básico
            [
                'module_id' => $hero->id,
                'label' => 'Título principal',
                'name' => 'title',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'Bienvenido a nuestro sitio',
                'is_required' => true,
                'order' => 1,
                'validation_rules' => json_encode(['required', 'string', 'max:100']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Subtítulo',
                'name' => 'subtitle',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'Descubre nuestros productos',
                'is_required' => false,
                'order' => 2,
                'validation_rules' => json_encode(['nullable', 'string', 'max:200']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Imagen de fondo
            [
                'module_id' => $hero->id,
                'label' => 'Imagen de fondo',
                'name' => 'background_image',
                'type' => 'image',
                'color_mode' => 'both',
                'placeholder' => 'URL de la imagen',
                'is_required' => true,
                'order' => 3,
                'validation_rules' => json_encode(['required', 'image', 'max:5120']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Control de imagen
            [
                'module_id' => $hero->id,
                'label' => 'Tamaño de la imagen',
                'name' => 'bg_image_size',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'cover',
                'is_required' => false,
                'order' => 4,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Posición de la imagen',
                'name' => 'bg_image_position',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'center',
                'is_required' => false,
                'order' => 5,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Repetir imagen',
                'name' => 'bg_image_repeat',
                'type' => 'toggle',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 6,
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Dimensiones
            [
                'module_id' => $hero->id,
                'label' => 'Altura mínima',
                'name' => 'hero_min_height',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '400',
                'is_required' => false,
                'order' => 7,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'options' => json_encode(['min' => 200, 'max' => 800, 'step' => 10, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Altura máxima',
                'name' => 'hero_max_height',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '800',
                'is_required' => false,
                'order' => 8,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'options' => json_encode(['min' => 400, 'max' => 1200, 'step' => 10, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Efectos
            [
                'module_id' => $hero->id,
                'label' => 'Parallax',
                'name' => 'enable_parallax',
                'type' => 'toggle',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 9,
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Velocidad parallax',
                'name' => 'parallax_speed',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '0.5',
                'is_required' => false,
                'order' => 10,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'options' => json_encode(['min' => 0.1, 'max' => 1, 'step' => 0.1, 'unit' => '']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Overlay
            [
                'module_id' => $hero->id,
                'label' => 'Activar overlay',
                'name' => 'enable_overlay',
                'type' => 'toggle',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 11,
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Color del overlay',
                'name' => 'overlay_color',
                'type' => 'color',
                'color_mode' => 'both',
                'placeholder' => '#000000',
                'is_required' => false,
                'order' => 12,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Opacidad del overlay',
                'name' => 'overlay_opacity',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '0.5',
                'is_required' => false,
                'order' => 13,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'options' => json_encode(['min' => 0, 'max' => 1, 'step' => 0.1, 'unit' => '']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Colores por modo
            [
                'module_id' => $hero->id,
                'label' => 'Color de fondo (modo claro)',
                'name' => 'bg_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#f5f5f5',
                'is_required' => false,
                'order' => 14,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Color de fondo (modo oscuro)',
                'name' => 'bg_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#1a1a1a',
                'is_required' => false,
                'order' => 15,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Color del texto (modo claro)',
                'name' => 'text_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#000000',
                'is_required' => false,
                'order' => 16,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Color del texto (modo oscuro)',
                'name' => 'text_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#ffffff',
                'is_required' => false,
                'order' => 17,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Botón
            [
                'module_id' => $hero->id,
                'label' => 'Texto del botón',
                'name' => 'button_text',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'Llamada a la acción',
                'is_required' => false,
                'order' => 18,
                'validation_rules' => json_encode(['nullable', 'string', 'max:50']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'URL del botón',
                'name' => 'button_url',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'https://ejemplo.com',
                'is_required' => false,
                'order' => 19,
                'validation_rules' => json_encode(['nullable', 'url']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Estilo del botón',
                'name' => 'button_style',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 20,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Layout
            [
                'module_id' => $hero->id,
                'label' => 'Alineación del contenido',
                'name' => 'content_alignment',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'center',
                'is_required' => false,
                'order' => 21,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Padding superior',
                'name' => 'padding_top',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '40',
                'is_required' => false,
                'order' => 22,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'options' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Padding inferior',
                'name' => 'padding_bottom',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '40',
                'is_required' => false,
                'order' => 23,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'options' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Component::insert($heroComponents);

        // Opciones para selects del Hero
        $heroSelects = [
            'bg_image_size' => [
                ['Cubrir', 'cover', 1],
                ['Contener', 'contain', 2],
                ['Automático', 'auto', 3],
                ['Estirar', '100% 100%', 4],
            ],
            'bg_image_position' => [
                ['Centro', 'center', 1],
                ['Superior', 'top', 2],
                ['Inferior', 'bottom', 3],
                ['Izquierda', 'left', 4],
                ['Derecha', 'right', 5],
                ['Superior izquierda', 'top left', 6],
                ['Superior derecha', 'top right', 7],
                ['Inferior izquierda', 'bottom left', 8],
                ['Inferior derecha', 'bottom right', 9],
            ],
            'button_style' => [
                ['Primario', 'primary', 1],
                ['Secundario', 'secondary', 2],
                ['Outline', 'outline', 3],
            ],
            'content_alignment' => [
                ['Izquierda', 'left', 1],
                ['Centro', 'center', 2],
                ['Derecha', 'right', 3],
            ],
        ];

        foreach ($heroSelects as $name => $options) {
            $component = Component::where('module_id', $hero->id)
                ->where('name', $name)
                ->first();
            
            if ($component) {
                foreach ($options as $index => $option) {
                    ComponentOption::insert([
                        'component_id' => $component->id,
                        'label' => $option[0],
                        'value' => $option[1],
                        'order' => $option[2],
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                }
            }
        }

        // ============================================
        // MÓDULO FOOTER PROFESIONAL
        // ============================================
        $footer = Module::create([
            'name' => 'Footer',
            'description' => 'Pie de página completamente dinámico con columnas configurables',
            'slug' => 'footer',
        ]);

        $footerComponents = [
            // Copyright
            [
                'module_id' => $footer->id,
                'label' => 'Texto de copyright',
                'name' => 'copyright_text',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => '© 2026 Tu Empresa. Todos los derechos reservados.',
                'is_required' => true,
                'order' => 1,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Colores por modo
            [
                'module_id' => $footer->id,
                'label' => 'Color de fondo (modo claro)',
                'name' => 'bg_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#f8f9fa',
                'is_required' => true,
                'order' => 2,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Color de fondo (modo oscuro)',
                'name' => 'bg_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#1a1a1a',
                'is_required' => true,
                'order' => 3,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Color del texto (modo claro)',
                'name' => 'text_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#333333',
                'is_required' => true,
                'order' => 4,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Color del texto (modo oscuro)',
                'name' => 'text_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#ffffff',
                'is_required' => true,
                'order' => 5,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Configuración de columnas
            [
                'module_id' => $footer->id,
                'label' => 'Número de columnas',
                'name' => 'columns_count',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '4',
                'is_required' => true,
                'order' => 6,
                'validation_rules' => json_encode(['required', 'numeric', 'min:1', 'max:6']),
                'data_source' => null,
                'options' => json_encode(['min' => 1, 'max' => 6, 'step' => 1, 'unit' => 'col']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Columnas del footer',
                'name' => 'footer_columns',
                'type' => 'external',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => true,
                'order' => 7,
                'validation_rules' => json_encode(['required', 'array']),
                'data_source' => env('ERP_API_URL') . '/footer-columns',
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Redes sociales
            [
                'module_id' => $footer->id,
                'label' => 'Redes sociales',
                'name' => 'social_networks',
                'type' => 'external',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 8,
                'validation_rules' => json_encode(['nullable', 'array']),
                'data_source' => env('ERP_API_URL') . '/social-networks',
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Mostrar redes sociales',
                'name' => 'show_social',
                'type' => 'toggle',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 9,
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Posición de redes sociales',
                'name' => 'social_position',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'bottom',
                'is_required' => false,
                'order' => 10,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Espaciado
            [
                'module_id' => $footer->id,
                'label' => 'Padding superior',
                'name' => 'padding_top',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '40',
                'is_required' => false,
                'order' => 11,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'options' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Padding inferior',
                'name' => 'padding_bottom',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '40',
                'is_required' => false,
                'order' => 12,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'options' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Borde
            [
                'module_id' => $footer->id,
                'label' => 'Mostrar borde superior',
                'name' => 'show_top_border',
                'type' => 'toggle',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 13,
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Color del borde',
                'name' => 'border_color',
                'type' => 'color',
                'color_mode' => 'both',
                'placeholder' => '#dee2e6',
                'is_required' => false,
                'order' => 14,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Ancho
            [
                'module_id' => $footer->id,
                'label' => 'Ancho del footer',
                'name' => 'footer_width',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'container',
                'is_required' => false,
                'order' => 15,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'options' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Component::insert($footerComponents);

        // Opciones para selects del Footer
        $socialPositionComp = Component::where('module_id', $footer->id)
            ->where('name', 'social_position')
            ->first();
        if ($socialPositionComp) {
            ComponentOption::insert([
                [
                    'component_id' => $socialPositionComp->id,
                    'label' => 'Superior',
                    'value' => 'top',
                    'order' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'component_id' => $socialPositionComp->id,
                    'label' => 'Inferior',
                    'value' => 'bottom',
                    'order' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'component_id' => $socialPositionComp->id,
                    'label' => 'En cada columna',
                    'value' => 'per_column',
                    'order' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        $footerWidthComp = Component::where('module_id', $footer->id)
            ->where('name', 'footer_width')
            ->first();
        if ($footerWidthComp) {
            ComponentOption::insert([
                [
                    'component_id' => $footerWidthComp->id,
                    'label' => 'Contenedor',
                    'value' => 'container',
                    'order' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'component_id' => $footerWidthComp->id,
                    'label' => 'Ancho completo',
                    'value' => 'full',
                    'order' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'component_id' => $footerWidthComp->id,
                    'label' => 'Contenedor fluido',
                    'value' => 'container-fluid',
                    'order' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }
    }
}