<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Sistema\Module;
use App\Models\Sistema\Component;


class ModuleSeeder extends Seeder
{
    public function run(): void
    {
        // ============================================
        // MÓDULO HEADER
        // ============================================
        $header = Module::create([
            'name' => 'Header',
            'description' => 'Encabezado del sitio con soporte para modo claro/oscuro',
            'slug' => 'header',
        ]);

        Component::insert([
            [
                'module_id' => $header->id,
                'label' => 'Logo (modo claro)',
                'name' => 'logo_light',
                'type' => 'image',
                'color_mode' => 'light',
                'placeholder' => 'URL del logo versión clara',
                'is_required' => true,
                'order' => 1,
                'validation_rules' => json_encode(['required', 'image', 'max:2048']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Logo (modo oscuro)',
                'name' => 'logo_dark',
                'type' => 'image',
                'color_mode' => 'dark',
                'placeholder' => 'URL del logo versión oscura',
                'is_required' => false,
                'order' => 2,
                'validation_rules' => json_encode(['nullable', 'image', 'max:2048']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Color de fondo (modo claro)',
                'name' => 'bg_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#f5f5f5',
                'is_required' => true,
                'order' => 3,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Color de fondo (modo oscuro)',
                'name' => 'bg_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#1a1a1a',
                'is_required' => true,
                'order' => 4,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Color del texto (modo claro)',
                'name' => 'text_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#000000',
                'is_required' => true,
                'order' => 5,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Color del texto (modo oscuro)',
                'name' => 'text_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#ffffff',
                'is_required' => true,
                'order' => 6,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Elementos del menú',
                'name' => 'menu_items',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 7,
                'validation_rules' => json_encode(['nullable', 'array']),
                'data_source' => 'menu-items',
                'configuration' => json_encode([
                    'is_multiple' => true,
                    'allow_clear' => true,
                    'placeholder' => 'Selecciona las páginas del menú'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Altura del header',
                'name' => 'header_height',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '80',
                'is_required' => false,
                'order' => 8,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 40, 'max' => 200, 'step' => 1, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $header->id,
                'label' => 'Posición del logo',
                'name' => 'logo_position',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'left',
                'is_required' => false,
                'order' => 9,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => json_encode([
                    'options' => [
                        ['value' => 'left', 'label' => 'Izquierda'],
                        ['value' => 'center', 'label' => 'Centro'],
                        ['value' => 'right', 'label' => 'Derecha'],
                    ]
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================
        // MÓDULO HERO
        // ============================================
        $hero = Module::create([
            'name' => 'Hero',
            'description' => 'Sección principal con control total de imagen, colores y efectos',
            'slug' => 'hero',
        ]);

        Component::insert([
            [
                'module_id' => $hero->id,
                'label' => 'Título principal',
                'name' => 'title',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'Bienvenido a nuestro sitio',
                'is_required' => true,
                'order' => 1,
                'validation_rules' => json_encode(['required', 'string', 'max:100']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Subtítulo',
                'name' => 'subtitle',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'Descubre nuestros productos',
                'is_required' => false,
                'order' => 2,
                'validation_rules' => json_encode(['nullable', 'string', 'max:200']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Imagen de fondo',
                'name' => 'background_image',
                'type' => 'image',
                'color_mode' => 'both',
                'placeholder' => 'URL de la imagen',
                'is_required' => true,
                'order' => 3,
                'validation_rules' => json_encode(['required', 'image', 'max:5120']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Tamaño de la imagen',
                'name' => 'bg_image_size',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'cover',
                'is_required' => false,
                'order' => 4,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => json_encode([
                    'options' => [
                        ['value' => 'cover', 'label' => 'Cubrir'],
                        ['value' => 'contain', 'label' => 'Contener'],
                        ['value' => 'auto', 'label' => 'Automático'],
                        ['value' => '100% 100%', 'label' => 'Estirar'],
                    ]
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Posición de la imagen',
                'name' => 'bg_image_position',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'center',
                'is_required' => false,
                'order' => 5,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => json_encode([
                    'options' => [
                        ['value' => 'center', 'label' => 'Centro'],
                        ['value' => 'top', 'label' => 'Superior'],
                        ['value' => 'bottom', 'label' => 'Inferior'],
                        ['value' => 'left', 'label' => 'Izquierda'],
                        ['value' => 'right', 'label' => 'Derecha'],
                        ['value' => 'top left', 'label' => 'Superior izquierda'],
                        ['value' => 'top right', 'label' => 'Superior derecha'],
                        ['value' => 'bottom left', 'label' => 'Inferior izquierda'],
                        ['value' => 'bottom right', 'label' => 'Inferior derecha'],
                    ]
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Repetir imagen',
                'name' => 'bg_image_repeat',
                'type' => 'toggle',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 6,
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Altura mínima',
                'name' => 'hero_min_height',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '400',
                'is_required' => false,
                'order' => 7,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 200, 'max' => 800, 'step' => 10, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Altura máxima',
                'name' => 'hero_max_height',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '800',
                'is_required' => false,
                'order' => 8,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 400, 'max' => 1200, 'step' => 10, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Color de fondo (modo claro)',
                'name' => 'bg_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#f5f5f5',
                'is_required' => false,
                'order' => 14,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Color de fondo (modo oscuro)',
                'name' => 'bg_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#1a1a1a',
                'is_required' => false,
                'order' => 15,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Color del texto (modo claro)',
                'name' => 'text_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#000000',
                'is_required' => false,
                'order' => 16,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Color del texto (modo oscuro)',
                'name' => 'text_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#ffffff',
                'is_required' => false,
                'order' => 17,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Texto del botón',
                'name' => 'button_text',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'Llamada a la acción',
                'is_required' => false,
                'order' => 18,
                'validation_rules' => json_encode(['nullable', 'string', 'max:50']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'URL del botón',
                'name' => 'button_url',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'https://ejemplo.com',
                'is_required' => false,
                'order' => 19,
                'validation_rules' => json_encode(['nullable', 'url']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Estilo del botón',
                'name' => 'button_style',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 20,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => json_encode([
                    'options' => [
                        ['value' => 'primary', 'label' => 'Primario'],
                        ['value' => 'secondary', 'label' => 'Secundario'],
                        ['value' => 'outline', 'label' => 'Outline'],
                    ]
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Alineación del contenido',
                'name' => 'content_alignment',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'center',
                'is_required' => false,
                'order' => 21,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => json_encode([
                    'options' => [
                        ['value' => 'left', 'label' => 'Izquierda'],
                        ['value' => 'center', 'label' => 'Centro'],
                        ['value' => 'right', 'label' => 'Derecha'],
                    ]
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Padding superior',
                'name' => 'padding_top',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '40',
                'is_required' => false,
                'order' => 22,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Padding inferior',
                'name' => 'padding_bottom',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '40',
                'is_required' => false,
                'order' => 23,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Padding derecha',
                'name' => 'padding_right',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '20',
                'is_required' => false,
                'order' => 24,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $hero->id,
                'label' => 'Padding izquierda',
                'name' => 'padding_left',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '20',
                'is_required' => false,
                'order' => 25,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        // ============================================
        // MÓDULO FOOTER
        // ============================================
        $footer = Module::create([
            'name' => 'Footer',
            'description' => 'Pie de página completamente dinámico con columnas configurables',
            'slug' => 'footer',
        ]);

        Component::insert([
            [
                'module_id' => $footer->id,
                'label' => 'Texto de copyright',
                'name' => 'copyright_text',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => '© 2026 Tu Empresa. Todos los derechos reservados.',
                'is_required' => true,
                'order' => 1,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Color de fondo (modo claro)',
                'name' => 'bg_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#f8f9fa',
                'is_required' => true,
                'order' => 2,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Color de fondo (modo oscuro)',
                'name' => 'bg_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#1a1a1a',
                'is_required' => true,
                'order' => 3,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Color del texto (modo claro)',
                'name' => 'text_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#333333',
                'is_required' => true,
                'order' => 4,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Color del texto (modo oscuro)',
                'name' => 'text_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#ffffff',
                'is_required' => true,
                'order' => 5,
                'validation_rules' => json_encode(['required', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Número de columnas',
                'name' => 'columns_count',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '4',
                'is_required' => true,
                'order' => 6,
                'validation_rules' => json_encode(['required', 'numeric', 'min:1', 'max:6']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 1, 'max' => 6, 'step' => 1, 'unit' => 'col']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Columnas del footer',
                'name' => 'footer_columns',
                'type' => 'external',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => true,
                'order' => 7,
                'validation_rules' => json_encode(['required', 'array']),
                'data_source' => 'footer-config',
                'configuration' => json_encode(['type' => 'builder', 'max_items' => 5]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Posición de redes sociales',
                'name' => 'social_position',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'bottom',
                'is_required' => false,
                'order' => 10,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => json_encode([
                    'options' => [
                        ['value' => 'top', 'label' => 'Superior'],
                        ['value' => 'bottom', 'label' => 'Inferior'],
                        ['value' => 'per_column', 'label' => 'En cada columna'],
                    ]
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Padding superior',
                'name' => 'padding_top',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '40',
                'is_required' => false,
                'order' => 11,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Padding inferior',
                'name' => 'padding_bottom',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '40',
                'is_required' => false,
                'order' => 12,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Mostrar borde superior',
                'name' => 'show_top_border',
                'type' => 'toggle',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 13,
                'validation_rules' => json_encode(['nullable', 'boolean']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Color del borde',
                'name' => 'border_color',
                'type' => 'color',
                'color_mode' => 'both',
                'placeholder' => '#dee2e6',
                'is_required' => false,
                'order' => 14,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $footer->id,
                'label' => 'Ancho del footer',
                'name' => 'footer_width',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'container',
                'is_required' => false,
                'order' => 15,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => json_encode([
                    'options' => [
                        ['value' => 'container', 'label' => 'Contenedor'],
                        ['value' => 'full', 'label' => 'Ancho completo'],
                        ['value' => 'container-fluid', 'label' => 'Contenedor fluido'],
                    ]
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================
        // MÓDULO HERO SPLIT
        // ============================================
        $heroSplit = Module::create([
            'name' => 'Hero Split',
            'description' => 'Sección con título y descripción a la izquierda e imagen a la derecha',
            'slug' => 'hero-split',
        ]);

        Component::insert([
            // ── Contenido ──────────────────────────────────────────────
            [
                'module_id' => $heroSplit->id,
                'label' => 'Título principal',
                'name' => 'title',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'Tu título principal aquí',
                'is_required' => true,
                'order' => 1,
                'validation_rules' => json_encode(['required', 'string', 'max:100']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Descripción',
                'name' => 'description',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'Escribe aquí una descripción detallada...',
                'is_required' => false,
                'order' => 2,
                'validation_rules' => json_encode(['nullable', 'string', 'max:600']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ── Imagen ─────────────────────────────────────────────────
            [
                'module_id' => $heroSplit->id,
                'label' => 'Imagen',
                'name' => 'image_url',
                'type' => 'image',
                'color_mode' => 'both',
                'placeholder' => 'URL de la imagen',
                'is_required' => true,
                'order' => 3,
                'validation_rules' => json_encode(['required', 'image', 'max:5120']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Texto alternativo de la imagen',
                'name' => 'image_alt',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'Descripción de la imagen para accesibilidad',
                'is_required' => false,
                'order' => 4,
                'validation_rules' => json_encode(['nullable', 'string', 'max:200']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Ajuste de la imagen',
                'name' => 'image_fit',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'cover',
                'is_required' => false,
                'order' => 5,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => json_encode([
                    'options' => [
                        ['value' => 'cover', 'label' => 'Cubrir'],
                        ['value' => 'contain', 'label' => 'Contener'],
                        ['value' => 'fill', 'label' => 'Rellenar'],
                        ['value' => 'none', 'label' => 'Ninguno'],
                    ]
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Radio de bordes de la imagen',
                'name' => 'image_border_radius',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '12',
                'is_required' => false,
                'order' => 6,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 48, 'step' => 2, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Ancho de la imagen (%)',
                'name' => 'image_width_percent',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '50',
                'is_required' => false,
                'order' => 7,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 30, 'max' => 70, 'step' => 5, 'unit' => '%']),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ── Botón ──────────────────────────────────────────────────
            [
                'module_id' => $heroSplit->id,
                'label' => 'Texto del botón',
                'name' => 'button_text',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'Llamada a la acción',
                'is_required' => false,
                'order' => 8,
                'validation_rules' => json_encode(['nullable', 'string', 'max:50']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'URL del botón',
                'name' => 'button_url',
                'type' => 'text',
                'color_mode' => 'both',
                'placeholder' => 'https://ejemplo.com',
                'is_required' => false,
                'order' => 9,
                'validation_rules' => json_encode(['nullable', 'url']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Estilo del botón',
                'name' => 'button_style',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => null,
                'is_required' => false,
                'order' => 10,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => json_encode([
                    'options' => [
                        ['value' => 'primary', 'label' => 'Primario'],
                        ['value' => 'secondary', 'label' => 'Secundario'],
                        ['value' => 'outline', 'label' => 'Outline'],
                    ]
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ── Layout ─────────────────────────────────────────────────
            [
                'module_id' => $heroSplit->id,
                'label' => 'Alineación vertical del contenido',
                'name' => 'content_vertical_alignment',
                'type' => 'select',
                'color_mode' => 'both',
                'placeholder' => 'center',
                'is_required' => false,
                'order' => 11,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => json_encode([
                    'options' => [
                        ['value' => 'top', 'label' => 'Superior'],
                        ['value' => 'center', 'label' => 'Centro'],
                        ['value' => 'bottom', 'label' => 'Inferior'],
                    ]
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Espacio entre columnas',
                'name' => 'gap',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '48',
                'is_required' => false,
                'order' => 12,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 120, 'step' => 8, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ── Colores ────────────────────────────────────────────────
            [
                'module_id' => $heroSplit->id,
                'label' => 'Color de fondo (modo claro)',
                'name' => 'bg_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#ffffff',
                'is_required' => false,
                'order' => 13,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Color de fondo (modo oscuro)',
                'name' => 'bg_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#1a1a1a',
                'is_required' => false,
                'order' => 14,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Color del texto (modo claro)',
                'name' => 'text_color_light',
                'type' => 'color',
                'color_mode' => 'light',
                'placeholder' => '#111111',
                'is_required' => false,
                'order' => 15,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Color del texto (modo oscuro)',
                'name' => 'text_color_dark',
                'type' => 'color',
                'color_mode' => 'dark',
                'placeholder' => '#ffffff',
                'is_required' => false,
                'order' => 16,
                'validation_rules' => json_encode(['nullable', 'string']),
                'data_source' => null,
                'configuration' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ── Padding ────────────────────────────────────────────────
            [
                'module_id' => $heroSplit->id,
                'label' => 'Padding superior',
                'name' => 'padding_top',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '60',
                'is_required' => false,
                'order' => 17,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Padding inferior',
                'name' => 'padding_bottom',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '60',
                'is_required' => false,
                'order' => 18,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Padding derecha',
                'name' => 'padding_right',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '40',
                'is_required' => false,
                'order' => 19,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => $heroSplit->id,
                'label' => 'Padding izquierda',
                'name' => 'padding_left',
                'type' => 'range',
                'color_mode' => 'both',
                'placeholder' => '40',
                'is_required' => false,
                'order' => 20,
                'validation_rules' => json_encode(['nullable', 'numeric']),
                'data_source' => null,
                'configuration' => json_encode(['min' => 0, 'max' => 200, 'step' => 5, 'unit' => 'px']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
